# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 823ca318d81d230809a1da5b500f09e64c9d1cb0b943f6934e8bc65df832ff491729ea0036ab127ba09509bf8a3d5aa0a5e9ff31e5683cb9f158c57b29b002a3

test:
  secret_key_base: c03cd32a4607435e0a98870edc283018c5316e3a86e7220ac5d61df8568ebc2050151c32821ab9a763f1d4d4464ba6f09718ea83854f4015cd2d57adc8f2a7ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
