require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AnketeController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Anketa. As you add validations to Anketa, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnketeController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ankete as @ankete" do
      anketa = Anketa.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ankete)).to eq([anketa])
    end
  end

  describe "GET show" do
    it "assigns the requested anketa as @anketa" do
      anketa = Anketa.create! valid_attributes
      get :show, {:id => anketa.to_param}, valid_session
      expect(assigns(:anketa)).to eq(anketa)
    end
  end

  describe "GET new" do
    it "assigns a new anketa as @anketa" do
      get :new, {}, valid_session
      expect(assigns(:anketa)).to be_a_new(Anketa)
    end
  end

  describe "GET edit" do
    it "assigns the requested anketa as @anketa" do
      anketa = Anketa.create! valid_attributes
      get :edit, {:id => anketa.to_param}, valid_session
      expect(assigns(:anketa)).to eq(anketa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Anketa" do
        expect {
          post :create, {:anketa => valid_attributes}, valid_session
        }.to change(Anketa, :count).by(1)
      end

      it "assigns a newly created anketa as @anketa" do
        post :create, {:anketa => valid_attributes}, valid_session
        expect(assigns(:anketa)).to be_a(Anketa)
        expect(assigns(:anketa)).to be_persisted
      end

      it "redirects to the created anketa" do
        post :create, {:anketa => valid_attributes}, valid_session
        expect(response).to redirect_to(Anketa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved anketa as @anketa" do
        post :create, {:anketa => invalid_attributes}, valid_session
        expect(assigns(:anketa)).to be_a_new(Anketa)
      end

      it "re-renders the 'new' template" do
        post :create, {:anketa => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested anketa" do
        anketa = Anketa.create! valid_attributes
        put :update, {:id => anketa.to_param, :anketa => new_attributes}, valid_session
        anketa.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested anketa as @anketa" do
        anketa = Anketa.create! valid_attributes
        put :update, {:id => anketa.to_param, :anketa => valid_attributes}, valid_session
        expect(assigns(:anketa)).to eq(anketa)
      end

      it "redirects to the anketa" do
        anketa = Anketa.create! valid_attributes
        put :update, {:id => anketa.to_param, :anketa => valid_attributes}, valid_session
        expect(response).to redirect_to(anketa)
      end
    end

    describe "with invalid params" do
      it "assigns the anketa as @anketa" do
        anketa = Anketa.create! valid_attributes
        put :update, {:id => anketa.to_param, :anketa => invalid_attributes}, valid_session
        expect(assigns(:anketa)).to eq(anketa)
      end

      it "re-renders the 'edit' template" do
        anketa = Anketa.create! valid_attributes
        put :update, {:id => anketa.to_param, :anketa => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested anketa" do
      anketa = Anketa.create! valid_attributes
      expect {
        delete :destroy, {:id => anketa.to_param}, valid_session
      }.to change(Anketa, :count).by(-1)
    end

    it "redirects to the ankete list" do
      anketa = Anketa.create! valid_attributes
      delete :destroy, {:id => anketa.to_param}, valid_session
      expect(response).to redirect_to(ankete_url)
    end
  end

end
